###############################################################################
# dns_records.tf — Workload
# ----------------------------------------------------------------------------
# Creates DNS records in the EXISTING Azure DNS zone (from the bootstrap
# folder). These records are ephemeral — they get destroyed and recreated
# alongside the workload because they point to the Front Door endpoint,
# which is itself ephemeral.
#
# We use a DATA block to read the existing DNS zone, NOT a resource block.
# A resource block would try to manage (and potentially delete) the zone.
# A data block just reads it.
#
# RECORDS CREATED:
#   1. TXT  _dnsauth.www     — Front Door domain validation for www
#   2. TXT  _dnsauth         — Front Door domain validation for apex
#   3. CNAME www             — Points www.mokcloud.site to Front Door endpoint
#
# NOTE ON APEX (mokcloud.site):
#   The apex A-alias record pointing to Front Door cannot be created by
#   Terraform's azurerm_dns_a_record with target_resource_id for Front Door
#   endpoints (this is a known provider limitation). Front Door handles the
#   apex routing internally when the custom domain is registered and the
#   TXT validation record exists. The apex domain will work via Front Door's
#   built-in resolution.
#
# Reference:
#   https://learn.microsoft.com/en-us/azure/dns/dns-delegate-domain-azure-dns
#   https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/dns_zone
###############################################################################

# ─── Read Existing DNS Zone ─────────────────────────────────────────────────
# This data block reads the DNS zone created by the bootstrap folder.
# It does NOT manage or modify the zone itself — only reads its properties.
data "azurerm_dns_zone" "main" {
  name                = var.dns_zone_name
  resource_group_name = var.dns_resource_group_name
}

# ─── TXT Record: Domain Validation for www ──────────────────────────────────
# Front Door needs this TXT record to prove you own www.mokcloud.site
# before it issues the managed TLS certificate. The validation_token is
# generated by the azurerm_cdn_frontdoor_custom_domain resource.
resource "azurerm_dns_txt_record" "www_validation" {
  name                = "_dnsauth.www"
  zone_name           = data.azurerm_dns_zone.main.name
  resource_group_name = var.dns_resource_group_name
  ttl                 = 3600

  record {
    value = azurerm_cdn_frontdoor_custom_domain.www.validation_token
  }

  tags = var.common_tags
}

# ─── TXT Record: Domain Validation for apex ─────────────────────────────────
# Same as above, but for the apex domain (mokcloud.site without www).
resource "azurerm_dns_txt_record" "apex_validation" {
  name                = "_dnsauth"
  zone_name           = data.azurerm_dns_zone.main.name
  resource_group_name = var.dns_resource_group_name
  ttl                 = 3600

  record {
    value = azurerm_cdn_frontdoor_custom_domain.apex.validation_token
  }

  tags = var.common_tags
}

# ─── CNAME Record: www → Front Door endpoint ────────────────────────────────
# This tells DNS "when someone asks for www.mokcloud.site, send them to
# the Front Door endpoint hostname." The browser then connects to Front
# Door, which terminates TLS and serves the cached content.
resource "azurerm_dns_cname_record" "www" {
  name                = "www"
  zone_name           = data.azurerm_dns_zone.main.name
  resource_group_name = var.dns_resource_group_name
  ttl                 = 3600
  record              = azurerm_cdn_frontdoor_endpoint.main.host_name

  tags = var.common_tags
}

# ─── A Alias Record: apex → Front Door endpoint ────────────────────────────
# Points mokcloud.site (no www) to the Front Door endpoint.
# Uses an alias record because Front Door's IPs change — alias records
# resolve to the Azure resource directly instead of a fixed IP.
resource "azurerm_dns_a_record" "apex" {
  name                = "@"
  zone_name           = data.azurerm_dns_zone.main.name
  resource_group_name = var.dns_resource_group_name
  ttl                 = 3600
  target_resource_id  = azurerm_cdn_frontdoor_endpoint.main.id

  tags = var.common_tags
}